# Generated by Django 4.1 on 2023-02-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portdent_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clients",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
