# Generated by Django 4.1 on 2023-02-23 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portdent_app", "0002_alter_clients_email"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Clients",
            new_name="Client",
        ),
    ]
