# Generated by Django 4.1 on 2023-02-26 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portdent_app", "0004_post"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="title_tag",
        ),
    ]
